indrasite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('join/', include('join.urls')),    
    path('admin/', admin.site.urls)
]

join/urls.py
from django.urls import path
from . import views

app_name = 'join'
urlpatterns = [
    path('', views.indexView.as_view(), name='indexView'),
    path('detail/<str:pk>/', views.detailView.as_view(), name='detailView'),
    path('write/', views.writeView.as_view(), name='writeView'),
    path('write/save', views.save, name='save')
]

join/models.py
from django.db import models
from django.utils import timezone
from django.contrib import admin
import datetime

# Create your models here.
class Member(models.Model) :
    mem_id = models.CharField(primary_key=True, max_length=30)
    mem_name = models.CharField(max_length=50)
    mem_age = models.SmallIntegerField()
    mem_join_date = models.DateTimeField('date published')

    #mem_id.verbose_name = "id"
    #mem_name.verbose_name = "이름"
    #mem_age.verbose_name = "나이"
    #mem_join_date.verbose_name = "가입일"

    @admin.display(
        boolean=True,
        ordering='mem_age',
        description='성인여부'
    )
    def isAdult(self) :
        return self.mem_age >= 20

    def add_ok_string(self) :
        return self.mem_name + "_ok"
    
    def __str__(self) :
        return self.mem_name

class Hobby(models.Model) :
    member = models.ForeignKey(Member, on_delete=models.CASCADE)
    hobby_text = models.CharField(max_length=200)

    #hobby_text.verbose_name = "취미"

    def __str__(self) :
        return self.hobby_text    

join/views.py
from typing import Generic
from django.db.utils import IntegrityError
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from .models import Member
from django.utils import timezone
from django.views import generic

# Create your views here.
class indexView(generic.ListView):
    template_name = 'join/index.html'
    context_object_name = 'member_list'

    def get_queryset(self) :

        """
        return Member.objects.filter(
            mem_join_date__lte=timezone.now()
        ).order_by('-mem_join_date')[:5]
        """
        return Member.objects.order_by('-mem_join_date')[:5]

class detailView(generic.DetailView) :
    model = Member
    template_name = 'join/detail.html'


class writeView(generic.TemplateView) :
    template_name = 'join/write.html'    

def save(request) :
    try :
        member = Member.objects.create(
            mem_id = request.POST['mem_id']
            , mem_name = request.POST['mem_name']
            , mem_age = request.POST['mem_age']   
            , mem_join_date = timezone.now()      
        )

        for hText in request.POST.getlist('hobby_text') :
            member.hobby_set.create(hobby_text=hText)
    except IntegrityError as e :
        return render(request, 'join/write.html', {
            'member': request.POST,
            'error_message': "이미 존재하는 아이디입니다. 다시 입력해주세요.",
        })
    except Exception as e :
        return render(request, 'join/write.html', {
            'member': request.POST,
            'error_message': "오류가 발생하였습니다.",
        })

    return HttpResponseRedirect(reverse('join:indexView'))

join/templates/base_site.html
{% extends "admin/base.html" %}

{% block title %}{% if subtitle %}{{ subtitle }} | {% endif %}{{ title }} | {{ site_title|default:_('Django site admin') }}{% endblock %}

{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">indra admin</a></h1>
{% endblock %}

{% block nav-global %}{% endblock %}

join/templates/join/detail.html
{% load static %}
<link rel="stylesheet" href="{% static 'join/css/style.css' %}" />
<script type="text/javascript" src="{% static 'join/js/join.js' %}"></script>
<div class="top-box">
  <a href="{% url 'join:indexView' %}" class="btn-02">뒤로</a>
  <div class="top-nick">indra</div>
</div>

<h1>{{ member.mem_id }}</h1>
<table class="tbl-view">
  <colgroup>
    <col width="100px" />
    <col width="*" />
  </colgroup>
  <tbody>
    <tr>
      <th>이름</th>
      <td>{{ member.mem_name }}</td>
    </tr>
    <tr>
      <th>나이</th>
      <td>{{ member.mem_age }}</td>
    </tr>
    <tr>
      <th>가입일</th>
      <td>{{ member.mem_join_date|date:'Y-m-d H:i:s'}}</td>
    </tr>
    <tr>
      <th>취미</th>
      <td>
        <div>
          {% for hobby in member.hobby_set.all %} {{ hobby.hobby_text }} {% endfor %}
        </div>
      </td>
    </tr>
  </tbody>
</table>

join/templates/join/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'join/css/style.css' %}" />
<script type="text/javascript" src="{% static 'join/js/join.js' %}"></script>
<div class="top-box">
  <a href="{% url 'join:writeView' %}" class="btn-01">가입</a>
  <div class="top-nick">indra</div>
</div>

{% if member_list %}
<table class="tbl-list">
  <colgroup>
    <col width="25%" />
    <col width="25%" />
    <col width="25%" />
    <col width="25%" />
  </colgroup>
  <thead>
    <tr>
      <th>아이디</th>
      <th>이름</th>
      <th>나이</th>
      <th>가입일</th>
    </tr>
  </thead>
  {% for member in member_list %}
  <tr
    onClick="javascript:join.goDetail('{% url 'join:detailView' member.mem_id %}');"
  >
    <td>{{ member.mem_id }}</td>
    <td>{{ member.mem_name }}</td>
    <td>{{ member.mem_age }}</td>
    <td>{{ member.mem_join_date|date:'Y-m-d H:i:s' }}</td>
  </tr>
  {% endfor %}
</table>
{% else %}
<p>No join data</p>
{% endif %}

join/templates/join/write.html
{% load static %}
<link rel="stylesheet" href="{% static 'join/css/style.css' %}" />
<script type="text/javascript" src="{% static 'join/js/join.js' %}"></script>
<div class="top-box">
  <a href="{% url 'join:indexView' %}" class="btn-02">뒤로</a>
  <div class="top-nick">indra</div>
</div>

<form action="{% url 'join:save' %}" method="post">
    {% csrf_token %}
    <table class="tbl-write">
        <colgroup>
            <col width="70px" />
            <col width="*" />
        </colgroup>
        <tbody>    
            <tr>
                <th>아이디</th>
                <td><input type="text" class="input01" name="mem_id" id="mem_id" /></td>        
            </tr>
            <tr>
                <th>이름</th>
                <td><input type="text" class="input01" name="mem_name" id="mem_name" /></td>        
            </tr>    
            <tr>
                <th>나이</th>
                <td><input type="number" class="input01" name="mem_age" id="mem_age" /></td>        
            </tr>     
        </tbody>   
    </table>
    <hr />

    <table class="tbl-write">
        <colgroup>
            <col width="70px" />
            <col width="*" />
        </colgroup>
        <tbody>    
            <tr>
                <th>취미</th>
                <td>
                    <ul class='mt-5'>
                        <li><input type="text" class="input01"  name="hobby_text" /></li>
                        <li><a href='#' name="btn_del_hobby" class="btn-03" onClick="javascript:join.delHobbyForm(this);">-</a></li>                
                        <li><a href='#' name="btn_add_hobby" class="btn-03" onClick="javascript:join.addHobbyForm(this);">+</a></li>                            
                    </ul>
                </td>        
            </tr>
        </tbody>   
    </table>
    <hr />

    <input type="submit" class="btn-04" value="저장" />

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

</form>